[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[prune]
  go-tests = true
  unused-packages = true
